### ISSUE TITLE
[LandingHeader.jsx] - add responsive landing page header

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#13]
## **Task Description**
Briefly describe the task or project.

### **Details**
(Please Provide Key Details, if required)
- Goals and objectives
- Deliverables
- Dependencies

### **Branch Name**
PR Should be made in `feature/LandingPage` Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### **Deadline**
Specify the task deadline.

### **Priority**
Set the priority: [High/Medium/Low]

## **Additional Details**
Add any other context about the task here.

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

## **Additional Details**
Add any other context about the task here.

**Comment by Atharva1723** [comment]
Can I work on this issue ?

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by CDCAman** [comment]
## Instructions

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCAman** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

## Instructions

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCAman** [comment]
> Can I work on this issue ? And why are the labels for gssoc not added in the issues

## Instructions

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by paulkrishanu4** [comment]
@thecuriousteam I would like to take on this task and create a responsive header for the website. I will ensure that the header looks good on all screen sizes and devices. Please assign this issue to me. under GSSOC'24

**Comment by thecuriousteam** [comment]
Yes @paulkrishanu4 you can start working on it

**Comment by AnitSarkar123** [comment]
@thecuriousteam can I start working on that issue

**Comment by CDCAman** [comment]
> @thecuriousteam can I start working on that issue 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by AnitSarkar123** [comment]
Is landing header means normal header of any website with responsiveness
