### ISSUE TITLE
[MeetingCards.jsx] - add responsive meeting card to the landing page

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#14]
## **Task Description**
Briefly describe the task or project.

### **Details**
(Please Provide Key Details, if required)
- Goals and objectives
- Deliverables
- Dependencies

### **Branch Name**
PR Should be made in `feature/LandingPage` Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### **Deadline**
Specify the task deadline.

### **Priority**
Set the priority: [High/Medium/Low]

## **Additional Details**
Add any other context about the task here.

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

## **Additional Details**
Add any other context about the task here.

**Comment by RishitaChourey** [comment]
Hey, I am Gssoc 24 contributor. Please assign me this issue.

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by CDCDhruv** [comment]
## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by manpreet244** [comment]
Want to work on this issue , pls assign me

**Comment by CDCAman** [comment]
@agxmbedi @manpreet244 
## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues
