### ISSUE TITLE
[LandingPage.jsx] - Create a Meeting Cards Component for the landing page.

### ISSUE THREAD

**Issue by CDCSuryaPratap** [Curious-Ecosystem/Curious-Connect#18]
# Task Description
In this issue we have to create the meetinng cards i.e. the component write below of the instant join room component of the landing page.

**Branch Name**

PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

**Goals and objectives**
Branch Name - feature/InitialUIdesign
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

**Deadline**
To be submitted by 15/05/2023

**Priority**
Medium

# Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

Instructions
You can start working on it by taking latest pull from main branch

- [ ]  Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ]  Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ]  Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ]  Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ]  Please attach the screenshots and video of the development work once it is done.
- [ ]  Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem.
- [ ]  please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number.

Respect Co Developers And Please Reach-out to admins if any issues.

**Comment by yash-tyagi-2003** [comment]
I want to  resolve this issue and contribute to this project under GSSOC 2024. Please assign it to me.

**Comment by paulkrishanu4** [comment]
I want to work on this issue please assign me

**Comment by CDCDhruv** [comment]
## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
@yash-tyagi-2003 ans @paulkrishanu4 you can start working please read instructions

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by mehtakevan** [comment]
Hello @CDCSuryaPratap , I would like to work on this issue under GSSOC'24, can you please assign it to me

**Comment by thecuriousteam** [comment]
@mehtakevan

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues
