### ISSUE TITLE
[OurTeam.jsx] - Create a OurTeam.jsx for the landing page component.

### ISSUE THREAD

**Issue by CDCRishabh** [Curious-Ecosystem/Curious-Connect#20]
## **Task Description**

In this issue we have to create the OurTeam Component  i.e. the component right below the features component of the landing page. Here We will display the team members.

## **Requirements:-**

Should be responsive.

## **Goals and objectives**

To achieve the required output.

## **Branch Name**
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

## **Deadline**
13/05/2024

## **Priority**
High

## Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by SumitKumar-17** [comment]
@CDCRishabh  I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by CDCDhruv** [comment]
## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by agxmbedi** [comment]
I am Agamjot Singh. Under GSSOC'24, I would like to work on this issue. Pls
assign me this!!

**Comment by CDCDhruv** [comment]
@yash-tyagi-2003 and @agxmbedi please read the instructions

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by CDCDhruv** [comment]
@Chandan157

## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by amresh012** [comment]
Hi , @CDCDhruv, Can I work On it?

**Comment by riddhi5474** [comment]
Hi sir. Under GSSOC'24, I would like to work on this issue

**Comment by mehtakevan** [comment]
Hello @CDCDhruv, I would like to work on this issue under GSSOC'24, can you please assign it to me.

**Comment by AnitSarkar123** [comment]
@thecuriousteam can I start working on that issue

**Comment by CDCAman** [comment]
> @thecuriousteam can I start working on that issue 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCAman** [comment]
> Hi sir. Under GSSOC'24, I would like to work on this issue
> 
> 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by niteshbca** [comment]
Please assign me task

**Comment by CDCNaman** [comment]
anu updates @agxmbedi  @Chandan157
