### ISSUE TITLE
[LandingPage.jsx] - Create a Features component for the landing page component.

### ISSUE THREAD

**Issue by CDCSuryaPratap** [Curious-Ecosystem/Curious-Connect#21]
# Task Description
In this issue we have to create the Features component of the landing page using the [Aceternity UI](https://ui.aceternity.com/) for the animations and also keep in mind that the design is responsive for all the devices that is for laptop screen as well as for the mobile devices.

### Branch Name

PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### Goals and objectives
Branch Name - feature/InitialUIdesign
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### Deadline
To be submitted by 15/05/2023

### Priority
Medium

# Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

Instructions
You can start working on it by taking latest pull from main branch

- [ ]  Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ]  Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ]  Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ]  Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ]  Please attach the screenshots and video of the development work once it is done
- [ ]  Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem
- [ ]  please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues.

**Comment by RishitaChourey** [comment]
Hey,I am a gssoc 24 contributor and would love to work on this. Pease assign me this issue.

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by CDCDhruv** [comment]
## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by yash-tyagi-2003** [comment]
I have done various projects in React.js and won hackathons in this Domain. I will be a great choice for this project and thus I request you to assign this to me for contribution under GSSOC 2024.

**Comment by agxmbedi** [comment]
I am Agamjot Singh. Under GSSOC'24, I would like to work on this issue. Pls
assign me this!!

**Comment by CDCDhruv** [comment]
@yash-tyagi-2003 and @agxmbedi please read the instructions

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by thecuriousteam** [comment]
@Chandan157 Please read the instructions

**Comment by riddhi5474** [comment]
Hi sir. Under GSSOC'24, I would like to work on this issue

**Comment by thecuriousteam** [comment]
@riddhi5474

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Comment by maha-sachin** [comment]
@CDCSuryaPratap , Hi can you help me to assign this issue?

**Comment by mehtakevan** [comment]
@thecuriousteam Can you please assign this issue to me under GSSOC24.

**Comment by thecuriousteam** [comment]
@mehtakevan you can start working on this

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by Nkmeoo7** [comment]
i am also want to work on this please assign me also
