### ISSUE TITLE
[Footer.jsx] - Create a Footer Component for Curious Connect-(Common)

### ISSUE THREAD

**Issue by CDCRishabh** [Curious-Ecosystem/Curious-Connect#22]
# Task Description
In this issue we have to create the Footer Component i.e. the component which will be common for the whole App.

**Branch Name**

PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

**Goals and objectives**
Branch Name - feature/InitialUIdesign
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

**Deadline**
To be submitted by 15/05/2023

**Priority**
Medium

# Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

Instructions
You can start working on it by taking latest pull from main branch

- [ ]  Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ]  Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ]  Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ]  Link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ]  Please attach the screenshots and video of the development work once it is done.
- [ ]  Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem.
- [ ]  please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number.

Respect Co Developers And Please Reach-out to admins if any issues.

**Comment by RishitaChourey** [comment]
Hey,I am a gssoc 24 contributor and would love to work on this. Pease assign me this issue.

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by yash-tyagi-2003** [comment]
I have done various projects in React.js and won hackathons in this Domain. I will be a great choice for this project and thus I request you to assign this to me for contribution under GSSOC 2024.

**Comment by thecuriousteam** [comment]
@yash-tyagi-2003

## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by a-nushka** [comment]
Hello, This is Anushka Desai I am a GSSOC 24 contributor, currently in Third Year of my engineering i have experience in react through various college and non college level projects . I would like you to assign this issue to me.thankyou

**Comment by thecuriousteam** [comment]
@a-nushka you can start working on it

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by sarthu210** [comment]
Hi sir i am sarthak here gssoc contributor can you assign this issue to me i am good at react you can check my previous work on GitHub

**Comment by CDCDhruv** [comment]
@sarthu210 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by thecuriousteam** [comment]
@Chandan157 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by sarthu210** [comment]
> @sarthu210
> 
> ## **Instructions**
> You can start working on it by taking latest pull from main branch
> 
> * [ ]  Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
> * [ ]  Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
> * [ ]  Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
> * [ ]  **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
> * [ ]  Please attach the screenshots and video of the development work once it is done
> * [ ]  Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem
> * [ ]  please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number
> 
> Respect Co Developers And Please Reach-out to admins if any issues

Thankyou!

**Comment by thecuriousteam** [comment]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Comment by RishithReddy9** [comment]
Hello sir! I would like to work on this issue

**Comment by CDCDhruv** [comment]
@RishithReddy9 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

**Comment by Akshatakapare** [comment]
I have done various projects and won hackathons in this Domain. I will be a great choice for this project so I request you to assign this to me for contribution under GSSOC 2024.

**Comment by thecuriousteam** [comment]
@Akshatakapare this component is done can you check other issue

@Chandan157 @sarthu210 @agxmbedi @RishitaChourey @yash-tyagi-2003

**Comment by thecuriousteam** [comment]
@RishithReddy9

**Comment by thecuriousteam** [comment]
## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
@Chandan157 @sarthu210 @agxmbedi @RishitaChourey @yash-tyagi-2003 @a-nushka @RishithReddy9 Please check other issue guys
