### ISSUE TITLE
[SignIn.jsx] - design an attractive signin page for curious connect

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#71]
## **Task Description**
Design an attractive signin page for curious connect

### **Details**
(Please Provide Key Details, if required)
- Please write your code inside the Component/Common directory and call it in Pages of root directory

### **Branch Name**
PR Should be made in `main` Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### **Deadline**
Specify the task deadline.

### **Priority**
Set the priority: [High/Medium/Low]

## **Additional Details**
Add any other context about the task here.

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by mehtakevan** [comment]
@thecuriousteam Can you please assign this issue to me

**Comment by sarthak-stranger** [comment]
@thecuriousteam Hi, can you please assign this issue to me. I have so experience in designing. And I made some temples already and worked on many projects, you can checkout my GitHub profile.

**Comment by thecuriousteam** [comment]
@mehtakevan @sarthak-stranger You can start working on it

**Comment by sarthak-stranger** [comment]
@thecuriousteam ok thank you, please assign also.

**Comment by thecuriousteam** [comment]
you can definitely  design by keeping some standards as per the requirement (The product is Curious Connect similar to google meet and zoom with lots of features

**Comment by AnitSarkar123** [comment]
Can I start solving the issue @thecuriousteam

**Comment by sarthu210** [comment]
I want work on this issue can you assign this to me also!

**Comment by thecuriousteam** [comment]
Sure @sarthu210
