### ISSUE TITLE
[SignUp.jsx] - design an attractive signup page for curious connect

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#72]
## **Task Description**
Design an attractive signup page for curious connect

### **Details**
(Please Provide Key Details, if required)
- Please write your code inside the Component/Common directory and call it in Pages of root directory

### **Branch Name**
PR Should be made in `main` Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

### **Deadline**
Specify the task deadline.

### **Priority**
High

## **Additional Details**
Add any other context about the task here.

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by mehtakevan** [comment]
@thecuriousteam Can you please assign this issue to me

**Comment by SkandSingh** [comment]
Hello, can you please assign me this issue. I would love to contribute to this under GSSoc'24

**Comment by Maxcillius** [comment]
Can I start working on this issue?

**Comment by rajsingh19** [comment]
@thecuriousteam Hi, can you please assign this issue to me. I have  already worked on  UI & UX enhanced templates . So I some have experience .
![IMG-20240513-WA0015](https://github.com/Curious-Ecosystem/Curious-Connect/assets/157736488/c150141c-4e98-44b8-84e6-c092714774cc)

**Comment by dhyaneshsiddhartha15** [comment]
Hi @thecuriousteam  I'm interested in contributing to the design of the SignUp page for Curious Connect. I'll work on creating an attractive and user-friendly layout that aligns with the overall design of the website.
Please let me know if there are any specific design elements or requirements I should consider while working on this task. I'm excited to collaborate on enhancing the user experience of the SignUp page! Assign me Under GSSOC'24 Label

**Comment by thecuriousteam** [comment]
@mehtakevan @SkandSingh @Maxcillius @rajsingh19 

You can start working on it

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by rajsingh19** [comment]
Thank you sir for  assignning me , for sign up page design will I get figma design or on what theme will I work?

**Comment by thecuriousteam** [comment]
you can definitely  design by keeping some standards as per the requirement (The product is Curious Connect similar to google meet and zoom with lots of fetures )

**Comment by rajsingh19** [comment]
@thecuriousteam okk sir

**Comment by AnitSarkar123** [comment]
Can I start solving the issue @thecuriousteam

**Comment by thecuriousteam** [comment]
Sure @AnitSarkar123

**Comment by vyakhyarastogi** [comment]
I would like to work upon this issue please assign me this task
