### ISSUE TITLE
Initial Postman Collection [Auth Service]

### ISSUE THREAD

**Issue by CDCNaman** [Curious-Ecosystem/Curious-Connect#90]
## **Task Description**

Create a Postman Collection for all the Routes of Curious Connect. 
As of now there are only 2 Routes created in Auth Service.

### **Details**
- Create a Postman Collection 
- Then Export this and put the generated file in the folder `apiInfo` in root directory

### **Priority**
Set the priority: Medium

## **Additional Details**
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/149701907/e779bea4-c660-424a-986e-7129765d0de8)

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

## **Additional Details**
Add any other context about the task here.

**Comment by Kairu-22** [comment]
Please assign this issue to me.

**Comment by CDCNaman** [comment]
@Kairu-22 you can start working on it

**Comment by thecuriousteam** [comment]
@Kairu-22 Please reach-out to admins

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCNaman** [comment]
PR Merged #204
